spring.application.name=account_service
server.port=8181
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${USER_SERVICE_DATABASE_URL}
#  jdbc:mysql://localhost:3306/accounts
spring.datasource.username=${USER_SERVICE_DATABASE_USERNAME}
#  account_user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
logging.level.org.springframework.security.*=TRACE
logging.level.org.springframework.web.*=TRACE
